//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlagsWP7.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TranslationsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlagsWP7.Localization.TranslationsResource", typeof(TranslationsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application helps you to recognize flags of all countries.
        ///
        ///In &quot;find a flag&quot; mode you just should select a few specific things which you can see on flag you can&apos;t recognize (colors, flag shape etc.) and tap the find button.
        ///
        ///In &quot;flags list&quot; mode there are lists of all flags sorted alphabetically and by continent.
        ///
        ///Have fun :).
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 1.1
        ///  Support to Polish language.
        ///
        ///version 1.0
        ///  Better algorithm, updates in interface.
        ///
        ///version 0.9
        ///  Completely new interface
        ///
        ///version 0.8
        ///  Changed application name. Only WP7 version. New history..
        /// </summary>
        public static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think that this application is useful and I should make it better and better, please buy full version. Thanks.
        ///
        ///If you need some functions or have any ideas, please tap link below and write about it in comment..
        /// </summary>
        public static string PlansIntro {
            get {
                return ResourceManager.GetString("PlansIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write comment and rate this app!.
        /// </summary>
        public static string PlansRateButton {
            get {
                return ResourceManager.GetString("PlansRateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My plans/ideas:
        ///1. Map in country details screen.
        ///2. Add some non-country flags (European Union, historical flags etc.).
        ///3. Support to other languages.
        ///4. Tests and some algorith
        ///5. Better graphics in &quot;find flag&quot; mode..
        /// </summary>
        public static string PlansText {
            get {
                return ResourceManager.GetString("PlansText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans.
        /// </summary>
        public static string PlansTitle {
            get {
                return ResourceManager.GetString("PlansTitle", resourceCulture);
            }
        }
    }
}
